server.port=8080
spring.application.name=bfhl-api

bfhl.user-id=aniket_singla_01102005
bfhl.email=aniket2100.be23@chitkara.edu.in
bfhl.roll-number=2310992100

spring.jackson.serialization.indent-output=false
